# Generated by Django 4.0 on 2023-03-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=200)),
                ('flier', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80)),
                ('sermon', models.FileField(upload_to='')),
                ('location', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=12)),
                ('testimony', models.TextField()),
            ],
        ),
    ]
