# Generated by Django 4.0 on 2023-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_event_sermon_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='')),
                ('download', models.ImageField(upload_to='')),
            ],
        ),
    ]
