# Generated by Django 4.0 on 2023-03-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Banner',
        ),
    ]
