# Generated by Django 4.0 on 2023-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_rename_photo_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='about',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='contact',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='donate',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='sermon',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='testimony',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
    ]
